### ISSUE TITLE
[documentation command] Ignore subcommand if we have subsubcommands

### ISSUE THREAD

**Issue by SimonRichardson** [juju/cmd#100]
A nice example of this is `juju wait-for`. This has 4 subcommands:

 - model
 - application
 - unit
 - machine

Instead, if we encounter a subcommand, with a set of subcommands, then just skip over the initial command and consume the sub-subcommands.

So:

 - juju
   - wait-for
     - model
     - application
     - unit
     - machine

Becomes:

 - juju
   - wait-for model
   - wait-for application
   - wait-for unit
   - wait-for machine

**Comment by barrettj12** [comment]
To enable this, we should add a `Subcommands` field to the `cmd.Info` struct, as Juan did recently with `Examples`.

**Comment by barrettj12** [comment]
I don't think we should "skip over the initial command", I think we should process both the initial command and its subcommands. In the case of `wait-for`, we should end up with these docs:
```
wait-for.md
wait-for_application.md
wait-for_model.md
wait-for_unit.md
wait-for_machine.md
```

**Comment by SimonRichardson** [comment]
@tmihoc might have something to say here.

Personally, I'm not actually sure what `wait-for.md` gives you. Maybe we can conceive of a high-level overview page, but as of right now, that'll just be a lot of fluff. Is it worth it, I'm not sure.

**Comment by barrettj12** [comment]
In the case of `wait-for`, you're right that the help text doesn't tell you much (currently).

As a general principle though, the supercommand help text might have some useful information we should capture. It's easy enough to ignore it as a reader anyway.

**Comment by SimonRichardson** [comment]
There should never be a subcommand of a subcommand. This was a mistake in the long term. We'll likely undo this in version 4, so that `wait-for application` isn't a subcommand, but a scope of `wait-for <scope>`.

**Comment by tmihoc** [comment]
Does `juju wait-for` do anything on its own? My understanding is that it does not. In that case, I wouldn't list it as a separate case.

@barrettj12 For some background: @SimonRichardson and I have discussed three options:

1. Keep it as it is, with subcommands. Not a good idea as we don't follow this pattern anywhere else.
2. Turn the subcommand into a scope argument. This is a good idea long term but not straightforward to implement.
3. Use each subcommand as the basis for a complete command. So, generate four commands. @SimonRichardson says it's a good interim solution to implement (I'm not sure I understand why), while still aiming for something like option 2 in the long term.

**Comment by SimonRichardson** [comment]
We know we want to get to 2. We know that we never want to do 1 (which is where we're at now). So if we just skip the commands that have sub-commands and just print them as if they were 2, then we get 2, without doing the work of 2.

**Comment by barrettj12** [comment]
I think you're both thinking about *just* the specific case of `wait-for`. I think we should be thinking about this more generally, because:
1. we don't know how the Juju CLI structure will evolve in the future
2. this is "a command line implementation framework", not "a subpackage of Juju". Nothing in here is (or should be) Juju-specific, including the `documentation` command. 

Hence, I think we should generate documentation for the command *and* its subcommands (and subcommands of those, etc).

It's also better to err on the side of "generate extra documentation", because it's easy to simply not sync a certain page to Discourse. Harder to change things later if we decide in the future that we actually need the `wait-for` doc.

> I'm not actually sure what wait-for.md gives you

At the very least, it's useful as an index page for the subcommands.

> There should never be a subcommand of a subcommand

Again, maybe true of the current Juju CLI, but maybe not true of other CLI tools using this library, and maybe not even true of the future Juju CLI!

**Comment by SimonRichardson** [comment]
> we don't know how the Juju CLI structure will evolve in the future

Then we'll change it then.

> this is "a command line implementation framework", not "a subpackage of Juju".

Then it's not fit for purpose and should be brought into Juju.

We're not building what juju requires and therefore it's a failure. Make it work for juju or don't. Pick one.
